########################################################################
#  ███████╗███████╗    ███████╗████████╗██╗   ██╗██████╗ ██╗ ██████╗   #
#  ██╔════╝██╔════╝    ██╔════╝╚══██╔══╝██║   ██║██╔══██╗██║██╔═══██╗  #
#  █████╗  ███████╗    ███████╗   ██║   ██║   ██║██║  ██║██║██║   ██║  #
#  ██╔══╝  ╚════██║    ╚════██║   ██║   ██║   ██║██║  ██║██║██║   ██║  #
#  ██║     ███████║    ███████║   ██║   ╚██████╔╝██████╔╝██║╚██████╔╝  #
#  ╚═╝     ╚══════╝    ╚══════╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝ ╚═════╝   #
########################################################################

#此為插件配置檔案
#VincentX0905(炸蝦)所開發之 Geyser用戶名轉暱稱 插件
#如有問題請加入 https://discord.fsbot.xyz 詢問

#可搭配顏色代碼與文字格式，讓文字更活潑!
#有關文字顏色與樣式請參考: https://minecraft.fandom.com/zh/wiki/格式化代码

#此項請勿更動
Version: "${project.version}"

Config:
  #是否總是更改玩家顯示名稱?(true)還是僅第一次加入伺服器時更改?(false)
  Always: false
  #前綴
  Nickname: "[BE]%s"

  #忽略的玩家
  Bypass-Player:
    - Notch
    #- VincentX0905_TW